[GOOGLE_CREDS]
type = "service_account"
project_id = "vibeque-app-project"
private_key_id = "6760793e47fdee609b0bdbbda0d10208e39c49bf"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCj0Gd/DEkWmtu/
+XBQ7X3VwFswm4dsV4MQNJodprnDl4JX7rDI7B0EsAT0hSglAL7TiIYkeDDW9DTG
PZnzCDBJF8vqOhyUJgVGxAhDmycJeCR+Bhwq8Gn+hNde4tYb9m961Q2Pf5tYRW1d
th+9c1kPDok+LuOTw992UQaMpyr/b7IbVMFGZNuye5RWiomZxKZNrzTNgdJ4WLlj
SdfKAhXx4bHJmy20rs0DhPmkY1WnnNuZk/7BQPIVQwLAw3e770z7HRx2KIOThIff
h9xhT1d0L0CvkAKAod6/8g1hk/X5b30e9eQ9fzVF/ZbXyBLl9LzJz+SYaQ2/WUR5
lcTx6klNAgMBAAECggEAETpUAsmGT5Pzs78w77c6T6Y425DPxODN44C/YIpDPm21
reJoFzQLDTjRx0F7FQEnZdRq1HULdd/IQ70AxCLCqT07xc4HaWaM5tdWTdMzCiI8
0ZV6QDh5J+T38tOvqXsuWDWwhRHqLXYHvXOaPPC07LTI/DrZgOsi74Iv9STeNxob
P41yXudq/0DYky6Y2t2Rw0uzoPahcmeMNMw+ZeEhQ2+zZ4mCUSJ8KUppp1gPedis
IIG9bb+DP973NDUyUjzI7H2FdXPmZCugvMLfhbX4lkvFC3U9FAHZig/gqkTPuyVa
DtpluVZmim8jbAMlyZKUfCUVlISscBZT4vHsh9a2ZQKBgQDcMBAISqbC8xB8Jo0j
nFXKFdhXpuLoU8OoS/oHsFBHKFgk7LARpxtshdmqbPfcZS1EU92dKlvFZI4ZXA4+
MHcC6plWiTDQyXaP36/LZ01xJf9bk+BIdFeYFKuzm1wS8/0SEn7KpkjxMNERr/xh
5VOaTbwMNWH0FxU1VXFN2CPMRwKBgQC+dR3MxHUQvLNLPsp/xkwocKNWXCiWYn/Z
FFLZ8EkcCRPTfLjS4fo9JthnG7jS6cIiqYtr/vvRwCmWKZlV8V+IrUo9r+dsXTNv
0dndB4V8N0Tnsx6A6dMKPbm2tlphSIk3Wc3hjVomfHFNKdRqPlv/YfUZ7wiy8Rlb
vn1nhZ3LywKBgDZytCQ4wZAHpxXsOo6JxDUavcq++/FTdViSoRtxoAhYk6Nd3BQh
bIijeLXKCGi5pD33Nx/8L4FaYkEnIGaEeYmBFbXuauHWT7k4KTJ1MxM9wC2XHakN
C/QReHwLePM+3l+vrybRg8wQtEJZcGGM4eWQP2YNdVF0u8vaexAy2HdVAoGAfxWC
xumn+30OXf0N/eiBVNKkCrH/2yjqih0Hk6jD/9MGya2FXiGvajKLX3GeCA42ng5n
m65OtYz1st8bE7+1sWuACF1hnGssMUbjiprENThj3/8jMX3Udhbt3r8a26Mc/DQO
Lpy1NM0AhS6OMD5gAK6Kb72SHmTGOPOIlhUQT7UCgYEApfpeJySQwMaSp1dkcECZ
1aowIp3svO5Etq5U5uWWyQsdSgv7jW/sDeK3QP924Y3Cg/6ICgnY3zXGMKqerIbg
CiUTAbjCy2X7G18oIr1FVDZ4S/WiUL5Rn69drCJkf6e3cBpFe/MxxjvTuAf8zGbu
Y6VuE2Tm2T0dxv/EuczIs0g=
-----END PRIVATE KEY-----"""
client_email = "vibeque-service@vibeque-app-project.iam.gserviceaccount.com"
client_id = "101904673318879264613"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/vibeque-service@vibeque-app-project.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
